version: '3.9'

services:
  python:
    image: akraradets/ait-ml-python:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./:/root/code
      - .vscode-server:/root/.vscode-server
  mlflow:
    image: akraradets/ait-ml-mlflow:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    volumes:
      - ./_mlflow:/mlflow
    ports:
      - 5000:5000