channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=23.2.1
- pip:
  - mlflow==2.8.1
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - matplotlib==3.7.2
  - numpy==1.25.2
  - packaging==21.3
  - pandas==1.5.3
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
name: mlflow-env
