name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
jobs:
#  unit_test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install Python and dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install python3 python3-pip -y
#          pip3 install scikit-learn==1.3.2
#          pip3 install numpy pytest

#      - name: Run unit tests
#        run: |
#          pytest --verbose app/test.py

  build_n_push:
#    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Compose services
        run: docker-compose -f docker-compose.yml pull

      # Add the "Build and Push" step here
      - name: Build and push Docker images
        run: |
          docker build -t tanziltonmoy/a3prediction:latest .
          docker push     tanziltonmoy/a3prediction:latest
      
 deploy:
    needs: build_n_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-85-95-151.compute-1.amazonaws.com "cd /home/ubuntu/A3CarPrediction && sudo docker-compose up -d"
